### ISSUE TITLE
Random generated password doesn't work

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1609]
https://github.com/GetLuna/Luna/issues/1606

**Comment by ListenerJubatus** [comment]
Yes, the user did try this after I did the update to 2.0.2, and the password did not seem to apply itself?

**Comment by Studio384** [comment]
I hope to get a fix this weekend, I'm terribly sorry for this inconvenience.

**Comment by Studio384** [comment]
Version 2.0.3 should solve this bug. I'm terribly sorry for the inconvenience and hope this improves your experience.

**Comment by ListenerJubatus** [comment]
It's unfortunate, but on my specific board it's still happening.
